### ISSUE TITLE
warning no module _tkinter

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem-deploy#27]
harmless? but annoying error message when debugging. probably just need to apt-get install tkinter as part of fabric or puppet

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/CherryPy-3.6.0-py3.4.egg/cherrypy/process/plugins.py", line 500, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/CherryPy-3.6.0-py3.4.egg/cherrypy/process/plugins.py", line 632, in run
    for filename in self.sysfiles() | self.files:
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/CherryPy-3.6.0-py3.4.egg/cherrypy/process/plugins.py", line 616, in sysfiles
    hasattr(m, '__loader__') and
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/six-1.5.2-py3.4.egg/six.py", line 116, in __getattr__
    _module = self._resolve()
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/six-1.5.2-py3.4.egg/six.py", line 105, in _resolve
    return _import_module(self.mod)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/six-1.5.2-py3.4.egg/six.py", line 76, in _import_module
    __import__(name)
  File "/home/vagrant/.pycharm_helpers/pydev/_pydev_imps/_pydev_pluginbase.py", line 445, in plugin_import
    fromlist, level)
  File "/home/vagrant/.pycharm_helpers/pydev/_pydev_imps/_pydev_pluginbase.py", line 445, in plugin_import
    fromlist, level)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 41, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package
```

**Comment by binary1230** [comment]
```apt-get install python3-tk``` does the trick
